name: Build Release Binaries

on:
  workflow_dispatch:
  
jobs:
	#生成的二进制上传到公开库
  sysnc-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 下载最新版本的资源文件
      - name: download latest release asset files
        uses: robinraju/release-downloader@v1.10
        with:
          # 当前私有库
          repository: 'ac169/FFmpeg-Builds-Legacy'
          latest: true
          token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
		  # 下载所有资源文件
          fileName: '*'

      - name: Check for new release
        run: echo "A new release was published"

      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          allowUpdates: true
          generateReleaseNotes: true  #自动生成发行说明。
          tag: "${{ github.ref_name }}"
          owner: "stars-one"
          repo: "XnApp-PC-Release"
          artifacts: '${{ github.workspace }}/*'
          token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
